### ISSUE TITLE
Can I feature this project in the ChimeraCSS readme?

### ISSUE THREAD

**Issue by MarkusJohansen** [f-ttok/f-ttok.github.io#1]
Hi! I am a maintainer of the CSS framework that this website was built upon. I were wondering whether I could get your permission to add this project to the list of featured projects, in the chimeracss readme 😄

**Comment by f-ttok** [comment]
@MarkusJohansen 
Thank you very much for the comment and your excellent CSS!
Of course, I gladly give my permission!😊😊

**Comment by f-ttok** [comment]
I apologize for not mentioning the licensing details earlier. I have now added them to README.
